// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN9fKKOi7P5WPzaZgUwUP_rSIO4ABJbco',
    appId: '1:1040305288347:web:35973ead46a7f342a4423e',
    messagingSenderId: '1040305288347',
    projectId: 'balungaonhs-29b22',
    authDomain: 'balungaonhs-29b22.firebaseapp.com',
    storageBucket: 'balungaonhs-29b22.firebasestorage.app',
    measurementId: 'G-MJJME8FR61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxkOf8XzdcVKGr4c0nahcYC0V1kgh86s',
    appId: '1:1040305288347:android:73aece1902fa2c66a4423e',
    messagingSenderId: '1040305288347',
    projectId: 'balungaonhs-29b22',
    storageBucket: 'balungaonhs-29b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBti4lYbKIQMRKlIhsJ79v0eYGFYshcg0I',
    appId: '1:1040305288347:ios:5d52a6cf07bbec17a4423e',
    messagingSenderId: '1040305288347',
    projectId: 'balungaonhs-29b22',
    storageBucket: 'balungaonhs-29b22.firebasestorage.app',
    iosBundleId: 'com.example.pbmaPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBti4lYbKIQMRKlIhsJ79v0eYGFYshcg0I',
    appId: '1:1040305288347:ios:5d52a6cf07bbec17a4423e',
    messagingSenderId: '1040305288347',
    projectId: 'balungaonhs-29b22',
    storageBucket: 'balungaonhs-29b22.firebasestorage.app',
    iosBundleId: 'com.example.pbmaPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN9fKKOi7P5WPzaZgUwUP_rSIO4ABJbco',
    appId: '1:1040305288347:web:52d640471e508f70a4423e',
    messagingSenderId: '1040305288347',
    projectId: 'balungaonhs-29b22',
    authDomain: 'balungaonhs-29b22.firebaseapp.com',
    storageBucket: 'balungaonhs-29b22.firebasestorage.app',
    measurementId: 'G-0T3XHN6H08',
  );
}
